### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Fixed typo in run command

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Hi, Gradle wrapper is launched with gradlew on Linux, MacOS and Windows. On which system are you working?

**Comment by ghost** [comment]
> Hi, Gradle wrapper is launched with gradlew on Linux, MacOS and Windows. On which system are you working?

M1 Monterey on a mac studio, zsh on Hyper.js terminal
Screen Shot 2022-06-19 at 12 21 18 PM

**Comment by MrStahlfelge** [comment]
Interesting, what happens when you enter `./gradlew ...`?

**Comment by nn-dmt** [comment]
> Interesting, what happens when you enter `./gradlew ...`?

It says 
```
zsh: command not found: gradlew
```

**Comment by ghost** [comment]
```
% ./gradlew bootRun
Downloading https://services.gradle.org/distributions/gradle-7.4.1-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.1!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.0)

2022-06-20 19:26:28.158  INFO 1411 --- [           main] o.e.e.p.PaymentportalApplicationKt       : Starting PaymentportalApplicationKt using Java 17.0.2 on M1-Studio.local with PID 1411 (/Users/michael/Documents/projects/ergopay-payment-portal/build/classes/kotlin/main started by michael in /Users/michael/Documents/projects/ergopay-payment-portal)
2022-06-20 19:26:28.160  INFO 1411 --- [           main] o.e.e.p.PaymentportalApplicationKt       : No active profile set, falling back to 1 default profile: "default"
2022-06-20 19:26:28.432  INFO 1411 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-06-20 19:26:28.454  INFO 1411 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 18 ms. Found 1 JPA repository interfaces.
2022-06-20 19:26:28.696  INFO 1411 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-06-20 19:26:28.700  INFO 1411 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-06-20 19:26:28.700  INFO 1411 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.63]
2022-06-20 19:26:28.753  INFO 1411 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-06-20 19:26:28.753  INFO 1411 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 569 ms
2022-06-20 19:26:28.816  INFO 1411 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-06-20 19:26:28.893  INFO 1411 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-06-20 19:26:28.914  INFO 1411 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-06-20 19:26:28.932  INFO 1411 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.9.Final
2022-06-20 19:26:29.006  INFO 1411 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-06-20 19:26:29.048  INFO 1411 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-06-20 19:26:29.185  INFO 1411 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-06-20 19:26:29.188  INFO 1411 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-06-20 19:26:29.472  WARN 1411 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-06-20 19:26:29.626  INFO 1411 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-06-20 19:26:29.631  INFO 1411 --- [           main] o.e.e.p.PaymentportalApplicationKt       : Started PaymentportalApplicationKt in 1.809 seconds (JVM running for 1.975)
<==========---> 83% EXECUTING [37s]
> :bootRun
```

**Comment by ghost** [comment]
Apparently, gradle when installed via Homebrew uses gradle as a command,

where your package wants ./gradlew

Strange

**Comment by ghost** [comment]
```
 % gradle -v

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Eclipse Adoptium 17.0.2+8)
OS:           Mac OS X 12.4 aarch64

% cd Documents/projects/ergopay-payment-portal 
ergopay-payment-portal % ./gradlew -v

------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Eclipse Adoptium 17.0.2+8)
OS:           Mac OS X 12.4 aarch64

% 
```

**Comment by MrStahlfelge** [comment]
Ok, cool. It is better to use gradlew as this uses the version that should be used with the project. Both work for you now as 7.4.1 and 7.4.2 are pretty similar, but that's not always the case.
Let's change to `./gradlew` on Linux and MacOS and `gradlew` on Windows then.

**Pull request closed without merging**
